[package]
name = "tux_async_example"
version = "0.1.0"
authors = ["loomaclin <loo.maclin@protonmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
tokio = { version = "0.1.15", features = ["async-await-preview"] }
